# Generated by Django 3.1 on 2020-08-19 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='messeage',
            new_name='message',
        ),
    ]
